### ISSUE TITLE
About crop 64 pixels in evaluation

### ISSUE THREAD

**Issue by weleslie** [YingqianWang/iPASSR#1]
Hi, thanks for your sharing! I wonder why the left view image needs to be cropped left 64 pixels for evaluation. It confuses me a lot, and I hope you can help me. Thank you for your kindness!

**Comment by YingqianWang** [comment]
Thanks for your comments. The cropping operation was first proposed in StereoSR and then followed by PASSRnet and SAM for performance evaluation. I guess, the authors of StereoSR may think that the leftmost 64 pixels in the left image cannot always find their correspondence in the right image, and cropping this boundary can augment the performance improvements introduced by the second view.

From my point of view, I think a good stereo image SR method should produce high-quality results on arbitrary spatial locations of both left and right images. To this end, we design a new evaluation approach in this paper to report the average PSNR and SSIM values on stereo images without any boundary cropping.

**Comment by weleslie** [comment]
Thanks for your apply! Now I understand the reason, and I think your approach can evaluate both left view image and right view image more fairly. Thanks again!
