### ISSUE TITLE
Some questions about the evaluation.

### ISSUE THREAD

**Issue by Orange066** [YingqianWang/iPASSR#7]
Excellent Work!! I recently use the code to conduct the stereo SR experiments, but I run the evaluation.m to test the performance and the code reports an error, as "conv2  cannot handle n-dimensional arrays, such as RGB images". Looking forward for your reply!

**Comment by YingqianWang** [comment]
I haven't met this error and the codes work well on my PC. Does this error occur when calculating SSIM scores?

**Comment by Orange066** [comment]
I found that as long as I modify this code ”ssim = ssim + ssim_index(im1(:,:,i), im2(:,:,i));“, it can be tested normally. But my test results are the same as yours on psnr, and are slight different on ssim.
